// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

type requestSubscriptionActiveSubscription struct {
	LimitId int `json:"limitId,omitempty"`
	Price   int `json:"price,omitempty"`
}

// Formal exchange type, please do not delete.
type responseSubscriptionActiveSubscription struct{}
