// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"
	"github.com/mbatimel/RabbitMQAndGolang/subscriptions/internal/interfaces"
)

type SubscriptionActiveSubscription func(ctx context.Context, limitId int, price int) (err error)

type MiddlewareSubscription func(next interfaces.Subscription) interfaces.Subscription

type MiddlewareSubscriptionActiveSubscription func(next SubscriptionActiveSubscription) SubscriptionActiveSubscription
