// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package externalapi

import (
	"context"
	"github.com/gofiber/fiber/v2"
	customhandlers "github.com/mbatimel/RabbitMQAndGolang/subscriptions/internal/transport/jsonRPC/custom-handlers"
)

func (http *httpSubscription) activeSubscription(ctx context.Context, request requestSubscriptionActiveSubscription) (response responseSubscriptionActiveSubscription, err error) {

	err = http.svc.ActiveSubscription(ctx, request.LimitId, request.Price)
	if err != nil {
		if http.errorHandler != nil {
			err = http.errorHandler(err)
		}
	}
	return
}
func (http *httpSubscription) serveActiveSubscription(ctx *fiber.Ctx) (err error) {

	var request requestSubscriptionActiveSubscription
	if err = ctx.BodyParser(&request); err != nil {
		ctx.Response().SetStatusCode(fiber.StatusBadRequest)
		_, err = ctx.WriteString("request body could not be decoded: " + err.Error())
		return
	}

	return customhandlers.ActiveSubscription(ctx, http.svc, request.LimitId, request.Price)
}
